### ISSUE TITLE
Implement RSS on Website

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/theme#16]
**Progress:**
- To Do ( ✔️ )
- In Progress (    )
- Review (    )
- Done (    )

**Repository:**
[devtranslate/devtranslate.github.io - branch develop](https://github.com/devtranslate/devtranslate.github.io/tree/develop)

**Description**
Because the site always changes or updates its content regularly, using RSS would make it easier for users to keep themselves informed of various updates.

***

**Portuguese Translate**
- Implementar RSS no website
**Descrição:** Pelo site sempre mudar ou atualizar o seu conteúdo regularmente, utilizar RSS facilitaria para os usuários se manterem informados sobre de diversas atualizações

**Comment by ribeiroevandro** [comment]
@larismourullo eu abri uma issue no repositório do site, sugerindo a migração do site que hoje está em Angular para Jekyll. Você aprovando isso, eu já dou o start nessa migração, mantendo o layout atual e já implementando o RSS.

**Comment by larismourullo** [comment]
@ribeiroevandro acabei de ver a issue, estarei respondendo por ela 👍
