### ISSUE TITLE
Implement Pocket on Website

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/theme#17]
**Progress:**
- To Do ( ✔️ )
- In Progress (    )
- Review (    )
- Done (    )

**Repository:**
[devtranslate/devtranslate.github.io](https://github.com/devtranslate/devtranslate.github.io)

**Description**
It's important to integrate the website as the pocket application so that the user can save the documents for future reading.

***

**Portuguese Translate**
- Implementar Pocket no website
**Descrição:** É importante integrar o website como o aplicativo pocket para o usuário poder salvar os documentos para ler futuramente.

**Comment by xRosbergx** [comment]
Irei começar a trabalhar nisso. Alguem poderia me adicionar no Skype xrosbergx@hotmail.com ou em algum outro meio de comunicação. Queria debater sobre alterações no projeto para expandir. 
Seria bem legal.

**Comment by xRosbergx** [comment]
Utilizo tecnologias Microsoft .net
