### ISSUE TITLE
Medium Writers

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/theme#26]
Nosso guia de contribuição: [CONTRIBUTING GUIDE](https://github.com/devtranslate/about/blob/master/CONTRIBUTING.md) 💃

**Comment by larismourullo** [comment]
@Douglaslt17 adicionado 👍

**Comment by crisgon** [comment]
@larismourullo sou iniciante no inglês ainda, mas consigo ler e traduzir algumas coisinhas. Queria contribuir enquanto estudo, mas precisaria da ajuda com revisão ou qualquer coisa do tipo. Será que assim rola? Se rolar, meu user do medium é @kristiano.gon

**Comment by iagocavalcante** [comment]
@iagoangelimc

**Comment by larismourullo** [comment]
Feito @iagocavalcante 👏

**Comment by raphaelminacio** [comment]
@raphaelminacio

Obrigado!!

**Comment by larismourullo** [comment]
@raphaelminacio adicionado 💃
